---
- src: https://github.com/cspicer/ansible-apt
  path: .vagrant/provisioners/ansible/roles/

- src: https://github.com/cspicer/ansible-runit
  path: .vagrant/provisioners/ansible/roles/

- src: https://github.com/cspicer/ansible-nodejs
  path: .vagrant/provisioners/ansible/roles/
